curl -X POST http://121.40.102.152:8080/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "type": 3,
    "model": "chat",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "who are you?"
      },
      {
        "role": "assistant",
        "content": "I am a chatbot."
      }
    ],
    "temperature": 0.7,
    "max_tokens": 1000,
    "stream": true
  }'


curl -X POST http://121.40.102.152:8080/v1/chat/completions \
  -H "Authorization: Bearer apple" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "chat",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "who are you?"
      },
      {
        "role": "assistant",
        "content": "I am a chatbot."
      }
    ],
    "temperature": 0.7,
    "max_tokens": 1000,
    "stream": true
  }'





curl -X POST http://localhost:8080/v1/chat/completions \
  -H "Authorization: Bearer apple" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "my",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "who are you?"
      },
      {
        "role": "assistant",
        "content": "I am a chatbot."
      }
    ],
    "temperature": 0.7,
    "max_tokens": 1000,
    "stream": true
  }'




# 1. 编译前端
cd web; pnpm install; $env:NEXT_PUBLIC_APP_VERSION="dev"; pnpm run build; cd ..
Move-Item -Force web\out static\out

# 2. 更新价格
python3 scripts/updatePrice.py

# 3. 编译 Go 后端
$env:GOOS="linux"; $env:GOARCH="amd64"; $env:CGO_ENABLED="0"
go build -o build/docker/linux/amd64/octopus -ldflags="-s -w" -tags=jsoniter .

# 4. 构建 Docker 镜像
docker build -f scripts/dockerfiles/Dockerfile.alpine -t jialtang/octopus:latest .


# docker run
docker run -d --name octopus-jialtang -v .\container\data:/app/data -p 8080:8080 jialtang/octopus:latest
docker save -o Docker_jialtang-octopus_latest.tar.gz jialtang/octopus:latest


pnpm run build ;


Remove-Item "static/out" -Recurse -Force -ErrorAction SilentlyContinue; Copy-Item web/out static/ -Recurse; go run main.go start 


update 